apiVersion: apps/v1
kind: Deployment

metadata:
  name: alertmanager

spec:
  replicas: 1

  selector:
    matchLabels:
      app: alertmanager

  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/alertmanager/configmap.yaml") . | sha256sum }}

      labels:
        app: alertmanager

    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false

      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}

          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL

          resources:
            {{- toYaml .Values.alertmanager.resources | nindent 12 }}

          args:
            - --config.file=/etc/alertmanager/alertmanager.yml

          ports:
            - name: http
              containerPort: 9093

          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: alertmanager-config