apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  selector:
    app: alertmanager
  ports:
    - name: http
      port: {{ .Values.alertmanager.service.port }}
      targetPort: http