apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana

spec:
  replicas: {{ .Values.grafana.replicaCount }}

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.grafana.service.port }}

          env:
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: {{ .Values.grafana.config.allowEmbedding | quote }}

            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: {{ .Values.grafana.config.anonymousEnabled | quote }}

            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: {{ .Values.grafana.config.anonymousOrgRole | quote }}

            - name: GF_USERS_VIEWERS_CAN_EDIT
              value: {{ .Values.grafana.config.viewersCanEdit | quote }}

            - name: GF_SERVER_ROOT_URL
              value: {{ .Values.grafana.config.rootURL | quote }}

            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: {{ .Values.grafana.config.serveFromSubPath | quote }}

          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true

            - name: provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true

            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
              readOnly: true

            - name: data
              mountPath: /var/lib/grafana

      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources

        - name: provisioning-dashboards
          configMap:
            name: grafana-provisioning-dashboards

        - name: dashboards
          configMap:
            name: grafana-dashboards

        - name: data
          persistentVolumeClaim:
            claimName: grafana-data