apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce

  {{- if .Values.grafana.storage.storageClass }}
  storageClassName: {{ .Values.grafana.storage.storageClass | quote }}
  {{- end }}
  
  resources:
    requests:
      storage: {{ .Values.grafana.storage.size }}