apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.grafana.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.grafana.storage.size }}