apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.prometheus.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}