apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: local-kubernetes
  namespace: signaldock
spec:
  provider:
    kubernetes:
      remoteNamespace: shared-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-local-reader