apiVersion: v1
kind: Secret
metadata:
  name: signaldock
type: Opaque
stringData:
  SIGNALDOCK_ADMIN_USERNAME: {{ required "secrets.signaldock.adminUsername is required" .Values.secrets.signaldock.adminUsername | quote }}
  SIGNALDOCK_ADMIN_PASSWORD: {{ required "secrets.signaldock.adminPassword is required" .Values.secrets.signaldock.adminPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
stringData:
  POSTGRES_DB: {{ required "secrets.postgres.database is required" .Values.secrets.postgres.database | quote }}
  POSTGRES_USER: {{ required "secrets.postgres.username is required" .Values.secrets.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ required "secrets.postgres.password is required" .Values.secrets.postgres.password | quote }}