apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.signaldock.name }}
type: Opaque
stringData:
  SIGNALDOCK_ADMIN_USERNAME: {{ .Values.secrets.signaldock.adminUsername | quote }}
  SIGNALDOCK_ADMIN_PASSWORD: {{ .Values.secrets.signaldock.adminPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres.name }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secrets.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}