apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signaldock-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sgrinan/signaldock.git
    targetRevision: main
    path: deploy/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: signaldock
  syncPolicy:
    automated:
      prune: true
      selfHeal: true