apiVersion: apps/v1
kind: Deployment

metadata:
  name: blackbox

spec:
  replicas: {{ .Values.blackbox.replicaCount }}

  selector:
    matchLabels:
      app: blackbox

  template:
    metadata:
      labels:
        app: blackbox

    spec:
      containers:
        - name: blackbox
          image: "{{ .Values.blackbox.image.repository }}:{{ .Values.blackbox.image.tag }}"
          imagePullPolicy: {{ .Values.blackbox.image.pullPolicy }}

          args:
            - "--config.file={{ .Values.blackbox.config.file }}"

          ports:
            - name: http
              containerPort: {{ .Values.blackbox.service.port }}

          volumeMounts:
            - name: config
              mountPath: {{ .Values.blackbox.config.file }}
              subPath: blackbox.yml
              readOnly: true
              
      volumes:
        - name: config
          configMap:
            name: blackbox