signaldock:
  replicaCount: 1
  image:
    repository: "ghcr.io/sgrinan/signaldock"
    tag: "d4c31b87bcf3fbc69248e27b94e379f206b0d436"
    pullPolicy: "IfNotPresent"
postgres:
  image:
    repository: "postgres"
    tag: "18.6"
    pullPolicy: "IfNotPresent"
  storage:
    size: "1Gi"
    storageClass: ""
blackbox:
  replicaCount: 1
  image:
    repository: "quay.io/prometheus/blackbox-exporter"
    tag: "v0.28.0"
    pullPolicy: "IfNotPresent"
prometheus:
  image:
    repository: "prom/prometheus"
    tag: "v3.14.0"
    pullPolicy: "IfNotPresent"
  storage:
    size: "2Gi"
    storageClass: ""
alertmanager:
  image:
    repository: "prom/alertmanager"
    tag: "v0.34.0"
    pullPolicy: "IfNotPresent"
grafana:
  image:
    repository: "grafana/grafana"
    tag: "13.2.1"
    pullPolicy: "IfNotPresent"
  storage:
    size: "1Gi"
    storageClass: ""
  config:
    anonymousEnabled: true
    anonymousOrgRole: "Viewer"
    viewersCanEdit: false
    rootURL: "http://localhost:8080/grafana/"
