secrets:
  signaldock:
    name: signaldock
    adminUsername: "admin"
    adminPassword: "change-me"

  postgres:
    name: postgres
    database: "signaldock"
    username: "signaldock"
    password: "change-me"