apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: signaldock
  namespace: signaldock
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: signaldock
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: signaldock/lab/signaldock
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres
  namespace: signaldock
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: postgres
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: signaldock/lab/postgres